# -*- coding: utf-8 -*-
"""stress detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w2uAUniWPzxgnqXUFaZJhT1b1c-hZk_s
"""

!pip install --upgrade keras tensorflow

import tensorflow as tf
from tensorflow.keras import layers, models

def build_my_model():
    # Initialize VGG16 base model without pre-trained weights and without the top classification layer
    base_model = tf.keras.applications.VGG16(
        weights=None, # Not using ImageNet pre-trained weights
        include_top=False, # Exclude the fully-connected layer at the top of the network
        input_shape=(224, 224, 3) # Define the input shape for images (height, width, channels)
    )

    # Create a Sequential model
    model = models.Sequential([
        layers.Input(shape=(224, 224, 3)), # Input layer specifying the shape of the input images
        base_model, # Add the VGG16 base model as a feature extractor
        layers.Flatten(), # Flatten the output of the base model into a 1D vector
        layers.Dense(128, activation='relu'), # A dense layer with 128 units and ReLU activation
        layers.Dropout(0.5), # Dropout layer to prevent overfitting, dropping 50% of units
        layers.Dense(1, activation='sigmoid') # Output dense layer with 1 unit and sigmoid activation for binary classification (Positive/Negative)
    ])

    return model

# Build the model
model = build_my_model()

try:
    # Attempt to load pre-trained weights from a file
    model.load_weights('model.weights.h5')
    print("Done")
except Exception as e:
    # If loading weights fails, print an error message
    print(f"weight error: {e}")
    print("check the name.")

import keras
import numpy as np
import cv2
from IPython.display import display, Javascript
from google.colab.output import eval_js
from base64 import b64decode
from google.colab.patches import cv2_imshow

def capture_and_predict(model):
  # JavaScript to handle webcam access, photo capture, and return base64 image data
  js = Javascript('''
    async function takePhoto(quality) {
      const div = document.createElement('div');
      const video = document.createElement('video');
      video.style.display = 'block';
      const stream = await navigator.mediaDevices.getUserMedia({video: true});

      const capture = document.createElement('button');
      capture.textContent = ' (Capture)';
      capture.style.cssText = 'padding: 10px; font-size: 16px; background: #4CAF50; color: white; border: none; cursor: pointer;';

      document.body.appendChild(div);
      div.appendChild(video);
      div.appendChild(capture);

      video.srcObject = stream;
      await video.play();

      await new Promise((resolve) => capture.onclick = resolve);

      const canvas = document.createElement('canvas');
      canvas.width = video.videoWidth;
      canvas.height = video.videoHeight;
      canvas.getContext('2d').drawImage(video, 0, 0);
      stream.getVideoTracks()[0].stop();
      div.remove();
      return canvas.toDataURL('image/jpeg', quality);
    }
    window.takePhoto = takePhoto;
    ''')
  display(js) # Display the JavaScript to enable webcam functionality

  # Take the photo using the JavaScript function and get base64 data
  data = eval_js('window.takePhoto(0.8)')
  # Decode the base64 string to binary image data
  binary = b64decode(data.split(',')[1])
  filename = 'photo.jpg'
  # Save the binary data as a JPEG file
  with open(filename, 'wb') as f:
    f.write(binary)

  # 2. Image Preprocessing for model input
  img = cv2.imread(filename) # Read the captured image using OpenCV
  img_resized = cv2.resize(img, (224, 224)) # Resize image to 224x224 pixels (model input size)
  img_normalized = img_resized.astype('float32') / 255.0 # Normalize pixel values to [0, 1]
  img_input = np.expand_dims(img_normalized, axis=0) # Add batch dimension (1, 224, 224, 3)

  # Perform prediction using the provided Keras model
  prediction_score = model.predict(img_input, verbose=0)[0][0]

  # Determine label and probability based on prediction score
  threshold = 0.5
  if prediction_score > threshold:
      label = "Stress"
      prob = prediction_score * 100
  else:
      label = "Not Stress"
      prob = (1 - prediction_score) * 100

  # Final output: Annotate and display the image
  color = (0, 0, 255) if label == "Stress" else (0, 255, 0) # Red for Stress, Green for Not Stress
  cv2.putText(img, f'{label}: {prob:.1f}%', (20, 50),
              cv2.FONT_HERSHEY_SIMPLEX, 1, color, 3) # Draw text on the original image

  cv2_imshow(img) # Display the annotated image in Colab
  print(f"(Raw Score): {prediction_score:.4f}") # Print the raw prediction score

# --- Main execution block ---
try:
    capture_and_predict(model) # Call the function to capture photo and predict
except NameError:
    print("model error: 'model' variable not found. Please ensure the model is built and loaded.")
except Exception as e:
    print(f"An error occurred: {e}")