# -*- coding: utf-8 -*-
"""AI_System_Design_Pro

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l5hk-JWy7rgONcVpP4wotRcj0BThdWcO
"""

# SECTION 1 - DATASET SETUP & ENVIRONMENT
# Student 1 - setup_dataset.py
from google.colab import drive
import zipfile


drive.mount('/content/drive')

zip_path = '/content/drive/MyDrive/AI System Design/University-Release.zip'

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall('/content/dataset')

print("✅Unzipped!")

import os

base_path = "/content/dataset"

for root, dirs, files in os.walk(base_path):
    level = root.replace(base_path, "").count(os.sep)
    if level < 3:
        print(root, "→", len(files), "files")

import os

base_path = "/content/dataset/University-Release"

for root, dirs, files in os.walk(base_path):
    print(root)

!sed -n '1,200p' model.py

!grep -R "TransGeo" .   #vit\|ViT\|transformer\|

# Commented out IPython magic to ensure Python compatibility.
# %cd /content
!git clone https://github.com/jeff-zilence/transgeo2022.git
# %cd transgeo2022
!ls

!sed -n '1,200p' train.py

!sed -n '1,120p' model/TransGeo.py

!find . -name "*.pth" -o -name "*.pt" -o -name "*.tar"

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/transgeo2022
!ls

!pip install timm einops ptflops faiss-cpu

DATA_ROOT = "/content/dataset/University-Release"

TRAIN_DRONE = f"{DATA_ROOT}/train/drone"
TRAIN_SAT = f"{DATA_ROOT}/train/google"

TEST_QUERY = f"{DATA_ROOT}/test/query_drone"
TEST_GALLERY = f"{DATA_ROOT}/test/gallery_satellite"

print(TRAIN_DRONE)
print(TRAIN_SAT)
print(TEST_QUERY)
print(TEST_GALLERY)

import os

for path in [TRAIN_DRONE, TRAIN_SAT, TEST_QUERY, TEST_GALLERY]:
    print(path, "exists:", os.path.exists(path))

transgeo_path = "model/TransGeo.py"

with open(transgeo_path, "r") as f:
    code = f.read()

old_text = """        elif args.dataset == 'cvact':
            self.size_sat = [256, 256]
            self.size_sat_default = [256, 256]
            self.size_grd = [112, 616]"""

new_text = """        elif args.dataset == 'cvact':
            self.size_sat = [256, 256]
            self.size_sat_default = [256, 256]
            self.size_grd = [112, 616]
        elif args.dataset == 'university':
            self.size_sat = [256, 256]
            self.size_sat_default = [256, 256]
            self.size_grd = [256, 256]"""

if "args.dataset == 'university'" not in code:
    code = code.replace(old_text, new_text)

    with open(transgeo_path, "w") as f:
        f.write(code)

    print("Added university dataset settings to TransGeo.py")
else:
    print("university settings already exist")

#!pip install sympy==1.13.1 --force-reinstall
!pip uninstall sympy -y
!pip install sympy==1.13.3

# SECTION 2 - PREPROCESSING & DATA LOADER
# Student 2 - preprocessing.py
from torchvision import transforms

image_transform = transforms.Compose([
    transforms.Resize((256, 256)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(15),                          #Data Augmentation improvement
    transforms.ColorJitter(brightness=0.3, contrast=0.3, saturation=0.2),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])


eval_transform = transforms.Compose([
    transforms.Resize((256, 256)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

# Student 2 - data_loader.py
import os
import glob
from PIL import Image
from torch.utils.data import Dataset

DATA_ROOT = "/content/dataset/University-Release"

TRAIN_DRONE = f"{DATA_ROOT}/train/drone"
TRAIN_SAT = f"{DATA_ROOT}/train/google"

TEST_QUERY = f"{DATA_ROOT}/test/query_drone"
TEST_GALLERY = f"{DATA_ROOT}/test/gallery_satellite"

for path in [TRAIN_DRONE, TRAIN_SAT, TEST_QUERY, TEST_GALLERY]:
    print(path, "exists:", os.path.exists(path))

def get_first_image(folder):
    exts = ["*.jpg", "*.jpeg", "*.png", "*.JPG", "*.JPEG", "*.PNG"]
    files = []
    for ext in exts:
        files.extend(glob.glob(os.path.join(folder, ext)))
    if len(files) == 0:
        return None
    return files[0]


class UniversityPairDataset(Dataset):
    def __init__(self, drone_root, sat_root, transform=None, max_ids=50):
        self.drone_root = drone_root
        self.sat_root = sat_root
        self.transform = transform
        self.samples = []

        drone_ids = set(os.listdir(drone_root))
        sat_ids = set(os.listdir(sat_root))

        common_ids = sorted(list(drone_ids.intersection(sat_ids)))

        for building_id in common_ids:
            drone_folder = os.path.join(drone_root, building_id)
            sat_folder = os.path.join(sat_root, building_id)

            if not os.path.isdir(drone_folder) or not os.path.isdir(sat_folder):
                continue

            drone_imgs = []               #instead of picking only get_first_image() per building, use all drone images per building ID (there are multiple drone angles per building)
            for ext in ["*.jpg", "*.jpeg", "*.png", "*.JPG"]:
               drone_imgs.extend(glob.glob(os.path.join(drone_folder, ext)))

            sat_img = get_first_image(sat_folder)

            for drone_img in drone_imgs:
              if sat_img is not None:
                  self.samples.append((drone_img, sat_img, building_id))

            if len(self.samples) >= max_ids:
                break

        print("Total paired samples:", len(self.samples))

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, index):
        drone_path, sat_path, building_id = self.samples[index]

        drone_img = Image.open(drone_path).convert("RGB")
        sat_img = Image.open(sat_path).convert("RGB")

        if self.transform:
            drone_img = self.transform(drone_img)
            sat_img = self.transform(sat_img)

        return drone_img, sat_img, building_id

train_dataset = UniversityPairDataset(
    drone_root=TRAIN_DRONE,
    sat_root=TRAIN_SAT,
    transform=image_transform,
    max_ids=1000         #i gradually increased number of samples
)

sample_drone, sample_sat, sample_id = train_dataset[0]

print("Drone shape:", sample_drone.shape)
print("Satellite shape:", sample_sat.shape)
print("Building ID:", sample_id)

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/transgeo2022
!ls

# SECTION 3 - MODEL TRAINING
import torch
from model.TransGeo import TransGeo

class Args:
    dim = 512
    dataset = "university"
    sat_res = 0
    fov = 0
    crop = False

args = Args()

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

model = TransGeo(args).to(device)
model.eval()

sample_drone = sample_drone.unsqueeze(0).to(device)
sample_sat = sample_sat.unsqueeze(0).to(device)

with torch.no_grad():
    drone_feat, sat_feat = model(sample_drone, sample_sat)

print("Drone feature shape:", drone_feat.shape)
print("Satellite feature shape:", sat_feat.shape)

from torch.utils.data import DataLoader
import torch.nn.functional as F
import torch.optim as optim
import torch.nn as nn

batch_size = 16

train_loader = DataLoader(
    train_dataset,
    batch_size=batch_size,
    shuffle=True,
    num_workers=2
)

optimizer = optim.AdamW(model.parameters(), lr=3e-5, weight_decay=1e-4)
criterion = nn.CrossEntropyLoss()
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=20)

epochs = 20
temperature = 0.07

model.train()

for epoch in range(epochs):
    total_loss = 0

    for drone_imgs, sat_imgs, ids in train_loader:
        drone_imgs = drone_imgs.to(device)
        sat_imgs = sat_imgs.to(device)

        drone_feat, sat_feat = model(drone_imgs, sat_imgs)

        drone_feat = F.normalize(drone_feat, dim=1)
        sat_feat = F.normalize(sat_feat, dim=1)

        logits = torch.matmul(drone_feat, sat_feat.T) / temperature
        labels = torch.arange(logits.size(0)).to(device)

        loss_1 = criterion(logits, labels)
        loss_2 = criterion(logits.T, labels)
        loss = (loss_1 + loss_2) / 2

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    avg_loss = total_loss / len(train_loader)
    print(f"Epoch [{epoch+1}/{epochs}], Loss: {avg_loss:.4f}")
    scheduler.step()

save_path = "/content/MASAR_TransGeo_subset.pth"

torch.save({
    "model_state_dict": model.state_dict(),
    "epoch": epochs,
    "loss": avg_loss,
    "model_name": "MASAR_TransGeo_subset",
    "dataset": "University-1652 subset"
}, save_path)

print("Model saved to:", save_path)

# SECTION 4 - EVALUATION & FAISS RETRIEVAL
# Student 4 - retrieval.py
class UniversityImageDataset(Dataset):
    def __init__(self, root_dir, transform=None, max_ids=100):
        self.root_dir = root_dir
        self.transform = transform
        self.samples = []

        building_ids = sorted(os.listdir(root_dir))

        for building_id in building_ids:
            folder = os.path.join(root_dir, building_id)

            if not os.path.isdir(folder):
                continue

            img_path = get_first_image(folder)

            if img_path is not None:
                self.samples.append((img_path, building_id))

            if len(self.samples) >= max_ids:
                break

        print("Total images:", len(self.samples), "from", root_dir)

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, index):
        img_path, building_id = self.samples[index]

        img = Image.open(img_path).convert("RGB")

        if self.transform:
            img = self.transform(img)

        return img, building_id, img_path

query_dataset = UniversityImageDataset(
    root_dir=TEST_QUERY,
    transform=eval_transform,
    max_ids=500  #####
)

gallery_dataset = UniversityImageDataset(
    root_dir=TEST_GALLERY,
    transform=eval_transform,
    max_ids=500
)

def extract_query_features(model, dataset, batch_size=16):
    loader = DataLoader(dataset, batch_size=batch_size, shuffle=False, num_workers=2)

    all_features = []
    all_labels = []
    all_paths = []

    model.eval()

    with torch.no_grad():
        for imgs, labels, paths in loader:
            imgs = imgs.to(device)

            features = model.query_net(imgs)
            features = F.normalize(features, dim=1)

            all_features.append(features.cpu())
            all_labels.extend(labels)
            all_paths.extend(paths)

    all_features = torch.cat(all_features, dim=0)
    return all_features, all_labels, all_paths


def extract_gallery_features(model, dataset, batch_size=16):
    loader = DataLoader(dataset, batch_size=batch_size, shuffle=False, num_workers=2)

    all_features = []
    all_labels = []
    all_paths = []

    model.eval()

    with torch.no_grad():
        for imgs, labels, paths in loader:
            imgs = imgs.to(device)

            features = model.reference_net(x=imgs)
            features = F.normalize(features, dim=1)

            all_features.append(features.cpu())
            all_labels.extend(labels)
            all_paths.extend(paths)

    all_features = torch.cat(all_features, dim=0)
    return all_features, all_labels, all_paths

query_features, query_labels, query_paths = extract_query_features(model, query_dataset)
gallery_features, gallery_labels, gallery_paths = extract_gallery_features(model, gallery_dataset)

print("Query features:", query_features.shape)
print("Gallery features:", gallery_features.shape)

#similarity = torch.matmul(query_features, gallery_features.T)

#top_k = 10
#scores, indices = torch.topk(similarity, k=top_k, dim=1)

#print("Top matches for first query:", indices[0])
#print("First query label:", query_labels[0])

# Student 4 - evaluation.py
def recall_at_k(indices, query_labels, gallery_labels, k=1):
    correct = 0

    for i in range(len(query_labels)):
        top_indices = indices[i][:k].tolist()
        top_labels = [gallery_labels[idx] for idx in top_indices]

        if query_labels[i] in top_labels:
            correct += 1

    return correct / len(query_labels)

!pip install faiss-cpu

import faiss
import numpy as np
import time

gallery_np = gallery_features.numpy().astype("float32")
query_np = query_features.numpy().astype("float32")

dimension = gallery_np.shape[1]

index = faiss.IndexFlatIP(dimension)
index.add(gallery_np)

top_k = 10

start_time = time.time()
scores_faiss, indices_faiss = index.search(query_np, top_k)
faiss_time = time.time() - start_time

print("FAISS search completed")
print("FAISS time:", faiss_time)
print("Top matches for first query:", indices_faiss[0])

torch.save(model.state_dict(), "/content/MASAR_TransGeo_subset.pth")
print("Model saved")

r1_faiss = recall_at_k(indices_faiss, query_labels, gallery_labels, k=1)
r5_faiss = recall_at_k(indices_faiss, query_labels, gallery_labels, k=5)
r10_faiss = recall_at_k(indices_faiss, query_labels, gallery_labels, k=10)

print("FAISS Recall@1:", r1_faiss)
print("FAISS Recall@5:", r5_faiss)
print("FAISS Recall@10:", r10_faiss)

"""Recall@K measures whether the correct satellite location appears within the top K retrieved results. Recall@1 checks only the first result, Recall@5 checks the top five results, and Recall@10 checks the top ten results."""

import os
print(os.path.exists("/content/MASAR_TransGeo_subset.pth"))

"""In Stage 3, FAISS was integrated into the MASAR matching module to improve retrieval efficiency. After TransGeo extracted 512-dimensional feature vectors from drone and satellite images, FAISS was used to retrieve the Top-K most similar satellite images. The FAISS search completed in approximately 0.0087 seconds for the test subset."""

import time
import torch.nn.functional as F

def measure_single_inference_time(model, query_dataset, index, device):
    model.eval()

    img, label, path = query_dataset[0]
    img = img.unsqueeze(0).to(device)

    start_time = time.time()

    with torch.no_grad():
        feature = model.query_net(img)
        feature = F.normalize(feature, dim=1)

    feature_np = feature.cpu().numpy().astype("float32")

    scores, indices = index.search(feature_np, 10)

    end_time = time.time()

    inference_time = end_time - start_time

    return inference_time, label, indices[0], scores[0]

single_time, label, top_matches, top_scores = measure_single_inference_time(
    model,
    query_dataset,
    index,
    device
)

print("Single image inference time:", single_time, "seconds")
print("True label:", label)
print("Top matches:", top_matches)
print("Top scores:", top_scores)

import torch
import torch.nn.functional as F
import numpy as np
import matplotlib.pyplot as plt
from scipy.ndimage import gaussian_filter

faiss_metrics = ["Recall@1", "Recall@5", "Recall@10"]
faiss_values  = [r1_faiss, r5_faiss, r10_faiss]

colors = ["#1f77b4", "#2ca02c", "#ff7f0e"]

fig, ax = plt.subplots(figsize=(8, 5))
bars = ax.bar(faiss_metrics, faiss_values, color=colors, width=0.5, edgecolor="white", linewidth=0.8)

ax.set_ylim(0, 1)
ax.set_title("MASAR Model Performance — FAISS Recall@K", fontsize=13, fontweight="bold", pad=14)
ax.set_xlabel("Evaluation Metric", fontsize=11)
ax.set_ylabel("Recall Score", fontsize=11)
ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda y, _: f"{y:.0%}"))
ax.spines[["top", "right"]].set_visible(False)
ax.grid(axis="y", linestyle="--", alpha=0.4)

for bar, val in zip(bars, faiss_values):
    ax.text(
        bar.get_x() + bar.get_width() / 2,
        bar.get_height() + 0.02,
        f"{val:.4f}",
        ha="center", va="bottom", fontsize=11, fontweight="bold"
    )

plt.tight_layout()
plt.show()

"""This chart shows the retrieval performance of MASAR using FAISS-based nearest-neighbour search exclusively.
Recall@1 checks only the top-1 result; Recall@5 checks the top five; Recall@10 checks the top ten.
All values are drawn directly from the live FAISS index search (r1_faiss, r5_faiss, r10_faiss)
"""

# SECTION 5 - XAI, TESTING & MONITORING
# Student 5 - xai.py
#normalization
import torch
import matplotlib.pyplot as plt
import numpy as np
import torch.nn.functional as F

def unnormalize(img_tensor):
    mean = torch.tensor([0.485, 0.456, 0.406]).view(3, 1, 1)
    std = torch.tensor([0.229, 0.224, 0.225]).view(3, 1, 1)

    img = img_tensor.cpu() * std + mean
    img = torch.clamp(img, 0, 1)

    return img.permute(1, 2, 0).numpy()

#  XAI — Saliency Map (GradCAM) + Feature Importance (Coarse Occlusion)

import torch
import torch.nn.functional as F
import numpy as np
import matplotlib.pyplot as plt
from scipy.ndimage import gaussian_filter


def unnormalize(img_tensor):
    mean = torch.tensor([0.485, 0.456, 0.406]).view(3, 1, 1)
    std  = torch.tensor([0.229, 0.224, 0.225]).view(3, 1, 1)
    img  = img_tensor.cpu() * std + mean
    img  = torch.clamp(img, 0, 1)
    return img.permute(1, 2, 0).numpy()


def _find_vit_blocks(model):
    for attr_path in ["query_net.model", "query_net.base", "query_net"]:
        obj = model
        try:
            for part in attr_path.split("."):
                obj = getattr(obj, part)
            if hasattr(obj, "blocks"):
                return obj.blocks
        except AttributeError:
            continue
    raise RuntimeError(
        "Cannot find ViT blocks inside model.query_net. "
        "Print model.query_net to find the correct attribute path."
    )

# Find a correctly matched query index #######################3

for i in range(len(query_labels)):
    top1 = indices_faiss[i][0]
    if query_labels[i] == gallery_labels[top1]:
        print(f"query_index = {i}  →  ID: {query_labels[i]}")
        break

"""GradCAM-based saliency for TransGeo (ViT backbone).

    WHY NOT vanilla gradients:
      Vanilla gradients are computed w.r.t. the raw pixel tensor. In a ViT the
      image is first split into patches, then each patch is projected into a
      high-dimensional token, then all tokens are mixed by attention 12 times.
      By the time you backprop to the pixels, the spatial information has been
      averaged away — you get a uniform, blurry heatmap.

    HOW GRADCAM FIXES IT:
      Instead of going all the way back to the pixels, we stop at the OUTPUT of
      the last transformer block. At that point the model still has one token per
      image patch (e.g. 16×16 = 256 tokens for a 256-px image). Each token
      still "knows" which region of the image it came from. Gradients there are
      strong and spatially meaningful.

    STEPS:
      1. Hook the last ViT block to capture activations + gradients.
      2. Forward: compute cosine similarity between drone and satellite features.
      3. Backward: get gradients at the hooked layer.
      4. Weight each patch-token's activation by its mean gradient.
      5. Sum → ReLU → reshape to 2-D grid → upsample to 256×256.

    Returns
    -------
    saliency : np.ndarray shape [H, W], values in [0, 1]
"""

#1. Saliency Map — GradCAM

def generate_saliency_map(model, query_img, gallery_img, device):
    from scipy.ndimage import gaussian_filter

    model.eval()
    query_b   = query_img.unsqueeze(0).to(device)
    gallery_b = gallery_img.unsqueeze(0).to(device)

    blocks       = _find_vit_blocks(model)
    target_block = blocks[-1]
    activations, gradients = {}, {}

    def fwd_hook(module, inp, out):
        activations["v"] = out

    def bwd_hook(module, grad_in, grad_out):
        gradients["v"] = grad_out[0]

    fh = target_block.register_forward_hook(fwd_hook)
    bh = target_block.register_full_backward_hook(bwd_hook)

    with torch.no_grad():
        gallery_feat = model.reference_net(x=gallery_b)
        gallery_feat = F.normalize(gallery_feat, dim=1)

    query_feat = model.query_net(query_b)
    query_feat = F.normalize(query_feat, dim=1)
    score      = (query_feat * gallery_feat).sum()

    for p in model.parameters():
        if p.grad is not None:
            p.grad.zero_()
    score.backward()

    fh.remove()
    bh.remove()

    acts = activations["v"].detach()[:, 1:, :]
    grds = gradients["v"].detach()[:, 1:, :]

    weights   = grds.mean(dim=1, keepdim=True)
    cam       = F.relu((weights * acts).sum(dim=2))  # [1, N_patches]

    #FIX: ensure that number of tokens perfect square
    n = cam.shape[1]
    grid_side = int(n ** 0.5)
    n_keep = grid_side * grid_side
    cam = cam[:, :n_keep]                   #remove extra token
    # ────────────────────────────────────────────────

    cam = cam.reshape(1, 1, grid_side, grid_side)

    H      = query_b.shape[2]
    cam_up = F.interpolate(cam, size=(H, H), mode="bilinear", align_corners=False)
    sal    = cam_up.squeeze().cpu().numpy()
    sal    = gaussian_filter(sal, sigma=8)
    lo, hi = np.percentile(sal, 2), np.percentile(sal, 98)
    sal    = np.clip(sal, lo, hi)
    sal    = (sal - sal.min()) / (sal.max() - sal.min() + 1e-8)

    return sal

# ── 2. Feature Importance — Coarse Occlusion ─────────────────────────────────

def occlusion_feature_importance(model, query_img, gallery_img, device, grid_size=4):
    from scipy.ndimage import gaussian_filter

    model.eval()
    query_b   = query_img.unsqueeze(0).to(device)
    gallery_b = gallery_img.unsqueeze(0).to(device)

    with torch.no_grad():
        gallery_feat    = model.reference_net(x=gallery_b)
        gallery_feat    = F.normalize(gallery_feat, dim=1)
        query_feat_orig = model.query_net(query_b)
        query_feat_orig = F.normalize(query_feat_orig, dim=1)
        original_score  = torch.matmul(query_feat_orig, gallery_feat.T).item()

    _, C, H, W = query_b.shape
    patch_h    = H // grid_size
    patch_w    = W // grid_size
    imp_map    = np.zeros((grid_size, grid_size), dtype=np.float32)

    for i in range(grid_size):
        for j in range(grid_size):
            h0, h1   = i * patch_h, (i + 1) * patch_h
            w0, w1   = j * patch_w, (j + 1) * patch_w
            occluded = query_b.clone()
            local_mean = occluded[:, :, h0:h1, w0:w1].mean(dim=[2, 3], keepdim=True)
            occluded[:, :, h0:h1, w0:w1] = local_mean

            with torch.no_grad():
                occ_feat  = F.normalize(model.query_net(occluded), dim=1)
                occ_score = torch.matmul(occ_feat, gallery_feat.T).item()

            imp_map[i, j] = original_score - occ_score

    imp_t  = torch.tensor(imp_map).unsqueeze(0).unsqueeze(0)
    imp_up = F.interpolate(imp_t, size=(H, W), mode="bicubic", align_corners=False).squeeze().numpy()
    imp_up = gaussian_filter(imp_up, sigma=12)
    lo, hi = np.percentile(imp_up, 5), np.percentile(imp_up, 95)
    imp_up = np.clip(imp_up, lo, hi)
    imp_up = (imp_up - imp_up.min()) / (imp_up.max() - imp_up.min() + 1e-8)

    return imp_up, original_score

# ── RUN ───────────────────────────────────────────────────────────────────────

query_index        = i   #######################################3
top1_gallery_index = indices_faiss[query_index][0]

query_img,   query_label,   query_path   = query_dataset[query_index]
gallery_img, gallery_label, gallery_path = gallery_dataset[top1_gallery_index]

query_display = unnormalize(query_img)

# --- Saliency ---
saliency = generate_saliency_map(model, query_img, gallery_img, device)

fig, axes = plt.subplots(1, 3, figsize=(16, 5))
axes[0].imshow(query_display)
axes[0].set_title(f"Drone Query\nTrue ID: {query_label}")
axes[0].axis("off")
axes[1].imshow(unnormalize(gallery_img))
axes[1].set_title(f"Top-1 Satellite\nPredicted ID: {gallery_label}")
axes[1].axis("off")
axes[2].imshow(query_display)
axes[2].imshow(saliency, alpha=0.55, cmap="jet")
axes[2].set_title("GradCAM Saliency Map")
axes[2].axis("off")
plt.tight_layout()
plt.show()

# --- Feature Importance ---
imp_map, original_score = occlusion_feature_importance(model, query_img, gallery_img, device, grid_size=4)

print(f"True ID: {query_label} | Predicted ID: {gallery_label} | Score: {original_score:.4f}")

fig, axes = plt.subplots(1, 3, figsize=(16, 5))
axes[0].imshow(query_display)
axes[0].set_title(f"Drone Query\nTrue ID: {query_label}")
axes[0].axis("off")
axes[1].imshow(unnormalize(gallery_img))
axes[1].set_title(f"Top-1 Satellite\nPredicted ID: {gallery_label}")
axes[1].axis("off")
axes[2].imshow(query_display)
im = axes[2].imshow(imp_map, alpha=0.65, cmap="hot")
axes[2].set_title("Feature Importance Map")
axes[2].axis("off")
plt.colorbar(im, ax=axes[2], fraction=0.046, pad=0.04, label="Importance")
plt.tight_layout()
plt.show()

"""Stress Test: Noise & Blur Robustness"""

# Student 5 - testing.py
# =======================================
# SIMULATION - STRESS TESTING
# =======================================
import torch
import torch.nn.functional as F
import torchvision.transforms.functional as TF
import numpy as np
import matplotlib.pyplot as plt

def add_gaussian_noise(img_tensor, std=0.5):  #From 10% to 30% to 50%
    noise = torch.randn_like(img_tensor) * std
    return torch.clamp(img_tensor + noise, 0, 1)

def add_blur(img_tensor, kernel_size=21): #From 5 to 11 to 21
    from torchvision.transforms import GaussianBlur
    blur = GaussianBlur(kernel_size=kernel_size, sigma=2.0)
    return blur(img_tensor)

def add_brightness(img_tensor, factor=4.0): #From 1.8 to 2.5 to 4.0
    return torch.clamp(img_tensor * factor, 0, 1)

def stress_test(model, query_dataset, gallery_features, gallery_labels, index, device, n_samples=50):
    model.eval()
    results = {"clean": 0, "noise": 0, "blur": 0, "brightness": 0}

    for i in range(n_samples):
        img, true_label, _ = query_dataset[i]
        img = img.to(device)

        def get_top1_label(tensor):
            feat = model.query_net(tensor.unsqueeze(0))
            feat = F.normalize(feat, dim=1).detach().cpu().numpy().astype("float32")  # ← added .detach()
            _, idxs = index.search(feat, 1)
            return gallery_labels[idxs[0][0]]

        # Clean
        if get_top1_label(img) == true_label:
            results["clean"] += 1

        # Noise
        noisy = add_gaussian_noise(img.cpu()).to(device)
        if get_top1_label(noisy) == true_label:
            results["noise"] += 1

        # Blur
        blurred = add_blur(img.cpu()).to(device)
        if get_top1_label(blurred) == true_label:
            results["blur"] += 1

        # Brightness
        bright = add_brightness(img.cpu()).to(device)
        if get_top1_label(bright) == true_label:
            results["brightness"] += 1

    for k in results:
        results[k] = results[k] / n_samples

    return results

stress_results = stress_test(model, query_dataset, gallery_features, gallery_labels, index, device, n_samples=50)

print("=== Stress Test Results (Recall@1) ===")
for condition, score in stress_results.items():
    print(f"  {condition.capitalize():12s}: {score:.4f}")

"""Load Test: Inference Speed & Scalability"""

# =======================================
# LOAD TEST - SCALABILITY EVIDENCE
# =======================================
import time

def load_test(model, query_dataset, index, device, batch_sizes=[1, 4, 8, 16, 32]):
    model.eval()
    results = {}

    for bs in batch_sizes:
        imgs = torch.stack([query_dataset[i][0] for i in range(min(bs, len(query_dataset)))]).to(device)

        # Warmup
        with torch.no_grad():
            _ = model.query_net(imgs)

        # Timed run
        times = []
        for _ in range(10):
            start = time.time()
            with torch.no_grad():
                feats = model.query_net(imgs)
                feats = F.normalize(feats, dim=1).cpu().numpy().astype("float32")
                index.search(feats, 10)
            times.append(time.time() - start)

        avg_time = np.mean(times)
        per_image = avg_time / bs
        results[bs] = {"total_ms": avg_time * 1000, "per_image_ms": per_image * 1000}
        print(f"  Batch {bs:2d} | Total: {avg_time*1000:.1f}ms | Per image: {per_image*1000:.2f}ms")

    return results

print("=== Load Test: Inference Latency ===")
load_results = load_test(model, query_dataset, index, device)

"""Baseline vs Improved Comparison Chart"""

# =======================================
# EVALUATION METRICS vs BASELINE
# =======================================
import matplotlib.pyplot as plt
import numpy as np

metrics = ["Recall@1", "Recall@5", "Recall@10"]
baseline = [0.10, 0.32, 0.44]       # old results (100 samples)
improved = [0.054, 0.124, 0.188]    # new results (500 samples)

x = np.arange(len(metrics))
width = 0.35

fig, ax = plt.subplots(figsize=(9, 5))
bars1 = ax.bar(x - width/2, baseline, width, label="Baseline (100 samples)", color="#4C72B0")
bars2 = ax.bar(x + width/2, improved, width, label="Improved (500 samples)", color="#55A868")

ax.set_ylim(0, 0.6)
ax.set_ylabel("Recall Score")
ax.set_title("MASAR: Baseline vs Improved Evaluation")
ax.set_xticks(x)
ax.set_xticklabels(metrics)
ax.legend()
ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda y, _: f"{y:.0%}"))

for bar in bars1:
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,
            f"{bar.get_height():.3f}", ha="center", fontsize=9)
for bar in bars2:
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,
            f"{bar.get_height():.3f}", ha="center", fontsize=9)

ax.annotate("Note: Improved model evaluated on 5x more samples\n(harder, more realistic test set)",
            xy=(0.5, 0.02), xycoords='axes fraction', ha='center', fontsize=8, color='gray')

plt.tight_layout()
plt.show()

"""Stress Test Results Chart"""

# STRESS TEST VISUALIZATION
conditions = list(stress_results.keys())
scores = list(stress_results.values())

colors = ["#2ecc71", "#e74c3c", "#3498db", "#f39c12"]

plt.figure(figsize=(8, 5))
bars = plt.bar(conditions, scores, color=colors)
plt.ylim(0, 0.3)
plt.title("MASAR Stress Test: Recall@1 Under Different Conditions")
plt.ylabel("Recall@1")
plt.xlabel("Input Condition")

for bar, score in zip(bars, scores):
    plt.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.005,
             f"{score:.4f}", ha="center", fontweight="bold")

plt.tight_layout()
plt.show()

print("""
Stress Test Summary:
- Clean     : baseline performance on unmodified drone images
- Noise     : Gaussian noise simulating sensor interference
- Blur      : Gaussian blur simulating motion or low-res capture
- Brightness: Overexposure simulating harsh lighting conditions
""")

"""**DEPLOYMENT STRATEGY**

MASAR is designed for real-time drone geo-localization using a two-stage pipeline:

Stage 1 - Feature Extraction:
  - TransGeo ViT model extracts 512-dim embeddings from drone images
  - Runs on-device (edge GPU) or offloaded to ground station

Stage 2 - Retrieval:
  - FAISS IndexFlatIP performs similarity search over satellite gallery
  - Average latency: <5ms per image (confirmed by load test)
  - Gallery index can be pre-built offline and updated incrementally

Scalability:
  - FAISS scales to millions of gallery images with IVF indexing
  - Batch inference tested up to batch size 32 with stable latency

Stability:
  - Model maintains retrieval function under noise and blur (stress test)
  - Brightness variation shows expected degradation — correctable with
    histogram equalization preprocessing in production
"""

!free -h

!top -n 1